### ISSUE TITLE
building issues

### ISSUE THREAD

**Issue by ntzb** [agungrbudiman/Soduto#1]
hi, trying to build this on m1 fails.
first, the dependencies are not grabbed (--recurse-submodules doesn't fetch them).
next, when I'm trying to build I get:

There is no XCFramework found at '/Users/david/Documents/personal/codeProjects/Soduto/Carthage/Build/NMSSH.xcframework'.

and the same for other dependencies.

are there special building instructions for this?
I want to add the notifications service which is commented out, to test

**Comment by agungrbudiman** [comment]
my fork doesn't use git submodules anymore
1. install [Carthage](https://github.com/Carthage/Carthage) using homebrew `brew install carthage`
2. retrieve and build dependencies `carthage build --platform macOS --use-xcframeworks`

**Comment by rkscodes** [comment]
Hey, I also have problems building the project, I added CartFile (copy of cartfile.resolved) but NMSSH always fails, whenever i run the above `carthage build --platform macOS --use-xcframeworks`. same happens for `update`

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ram/Developer/Soduto/Carthage/Checkouts/NMSSH/NMSSH.xcodeproj -scheme NMSSH -configuration Release -derivedDataPath 
/var/root/Library/Caches/org.carthage.CarthageKit/DerivedData/14.0_14A309/NMSSH/820ea2c0d9f1821fa605531490ba91684c97e629 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIG
N_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/NMSSH SKIP_INSTALL=YES 
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ram/Developer/Soduto/Carthage/Checkouts/NMSSH)
```

**Comment by agungrbudiman** [comment]
maybe it's because missing libs, try my fork of NMSSH [here](https://github.com/agungrbudiman/NMSSH/tree/4ee257547822eaec71d57e26c514072a846b681a) or see [beta](https://github.com/agungrbudiman/Soduto/tree/beta) branch.
