### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by electr1fy0** [agungrbudiman/Soduto#6]
CPU uses gets stuck at least 0.1 percent when not actively being used.

This only happens when Soduto has executed at least one task after launch. 
Before that, it's 0 percent usage when inactive which is why I feel this could be a bug.
Screenshot:
<img width="564" alt="Screenshot 2022-11-29 at 1 34 28 PM" src="https://user-images.githubusercontent.com/87616300/204472956-a9507abe-b07d-4594-9904-c40c7aa2c62e.png">

**Comment by agungrbudiman** [comment]
Soduto consume so little cpu when idle maybe it's normal. You could always try send ping from the phone to make sure soduto still listening.
